services:
    repository.email:
        class: PaneeDesign\DatabaseSwiftMailerBundle\Entity\EmailRepository
        factory: ['@doctrine.orm.default_entity_manager',getRepository]
        arguments: ['PedDatabaseSwiftMailerBundle:Email']
    ped.database.swift_mailer.spool:
        class: PaneeDesign\DatabaseSwiftMailerBundle\Spool\DatabaseSpool
        arguments: ['@repository.email', '%ped_database_swift_mailer.params%']
    swiftmailer.spool.db:
        alias: ped.database.swift_mailer.spool
    swiftmailer.mailer.default.spool.db:
        alias: ped.database.swift_mailer.spool