services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    PaneeDesign\DatabaseSwiftMailerBundle\Repository\EmailRepository: ~

    PaneeDesign\DatabaseSwiftMailerBundle\Repository\EmailRepositoryInterface: '@PaneeDesign\DatabaseSwiftMailerBundle\Repository\EmailRepository'

    Doctrine\ORM\EntityManagerInterface $emailManager: "@=service(container.getParameter('ped_database_swift_mailer.entity_manager'))"

    ped.database.swift_mailer.spool:
        class: PaneeDesign\DatabaseSwiftMailerBundle\Spool\DatabaseSpool
        bind:
            $parameters:
                max_retries: '%env(int:SMD_MAX_RETRIES)%'
                delete_sent_messages: '%env(bool:SMD_DELETE_SENT_MESSAGES)%'
                entity_manager: '%env(bool:SMD_ENTITY_MANAGER)%'
                auto_flush: '%env(bool:SMD_AUTO_FLUSH)%'

    swiftmailer.spool.db:
        alias: ped.database.swift_mailer.spool

    swiftmailer.mailer.default.spool.db:
        alias: ped.database.swift_mailer.spool
